#cloud-config
users:
  - default
  - name: ${USERNAME}
    sudo: false
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBKEY}

timezone: UTC
locale: "en_US.UTF-8"

package_update: true
package_upgrade: true
package_reboot_if_required: true

final_message: |
  ==========   TOWER SETUP COMPLETED IN $UPTIME secs    ==========
  The security of this environment has not been verified!
  You are still trusting the hypervisor/infrastructure provider.
  For full-privacy, enable Remote Attestation with CanaryBit Inspector.