#cloud-config
hostname: ${HOSTNAME}
users:
  - default
  - name: ${USERNAME}
    sudo: false
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBKEY}

timezone: UTC
locale: "en_US.UTF-8"

package_update: true
package_upgrade: true
package_reboot_if_required: true

final_message: |
  ==========   CANARYBIT TOWER SETUP COMPLETED IN $UPTIME secs    ==========
  The security and privacy of this environment is not verified! 
  You are still trusting the hypervisor/infrastructure provider. Use CanaryBit Remote Attestation service to unlock full privacy:
  ${CBINSPECTOR_URL}
  